config/routes.rb
Mol::Application.routes.draw do

  namespace :admin do
    root :to => "base#index"
    resources :partners
    resources :users
    resources :uploads
  end

  devise_for :users
  resources :partners do
    resources :items
    resources :file_uploads
  end

  resources :chassises
  match '/help', :to => 'pages#help', :via => 'get'
  root :to => "pages#index"

end

app/models/partner.rb
class Partner < ActiveRecord::Base

	validates :name, uniqueness: true, :presence => true
	validates :details, uniqueness: true, :presence => true

	has_many :items, :dependent => :destroy
	has_many :file_uploads, :dependent => :destroy
end

app/controllers/admin/partners_controller.rb
class Admin::PartnersController < Admin::BaseController

	def index
		@partners = Partner.all
	end

	def new
		@partner = Partner.new
	end

	def create
		@partner = Partner.new(partner_params)
		if @partner.save
			flash[:notice] = "Create new partners."
			redirect_to admin_partners_path
		else
			flash[:alert] = "Error on creating partners."
			render :action => 'new'
		end
	end

	def show
		@partner = Partner.find(params[:id])
	end

	def edit
		@partner = Partner.find(params[:id])
	end

	def update
		@partner = Partner.find(params[:id])
		if @partner.update(partner_params)
			flash[:notice] = "Update partner."
			redirect_to admin_partners_path		
		else
			flash[:alert] = "Error on updating partners."
			render :action => 'edit'
		end
	end

	def destroy
		@partner = Partner.find(params[:id]).destroy
		flash[:notice] = "Deleted partner."
		redirect_to admin_partners_path
	end

	private
		def partner_params
			params.require(:partner).permit(:name, :details)
		end
end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController

	def show
		@partners = Partner.all
		@partner = Partner.find(params[:id])
		@items = @partner.items
		@file_upload = @partner.file_uploads.build
	end
end

app/views/admin/partners/_form.html.erb
<%= form_for [:admin, @partner] do |f| %>
	<p>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.label :details %>
		<%= f.text_area :details %>
	</p>
	<%= f.submit %>
<% end %>

app/views/admin/partners/edit.html.erb
<h4>Update Partner</h4>
<%= render 'form' %>

app/views/admin/partners/index.html.erb
<h4>Partners List</h4>
<%= link_to "Create Partner Company", new_admin_partner_path %>

<table class="table">
	<thead>
		<tr>
			<th>Name</th>
			<th>Details</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
		<% @partners.each do |partner| %>
		<tr>
			<td><%= partner.name %></td>
			<td><%= partner.details %></td>
			<td>
				<%= link_to "View", [:admin, partner] %>
				<%= link_to "Update", [:edit, :admin, partner] %>
				<%= link_to "Delete", [:admin, partner], :method => :delete, :confirm => "Are you sure?" %>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/admin/partners/new.html.erb
<h4>New Partner Company</h4>
<%= render 'form' %>

app/views/admin/partners/show.html.erb
<h4>Partner Details</h4>
<h6>#<%= @partner.id %></h6>
<h6><%= @partner.name %></h6>
<h6><%= @partner.details %></h6>