config/routes.rb
Mol::Application.routes.draw do

  namespace :admin do
    root :to => "base#index"
    resources :partners
    resources :users
    resources :uploads
  end

  devise_for :users
  resources :partners do
    resources :items
    resources :file_uploads
  end

  resources :chassises
  match '/help', :to => 'pages#help', :via => 'get'
  root :to => "pages#index"

end

app/views/shared/_flash_message.html.erb
<% flash.each do |key, value| %>
	<div class='flash' id='<%= key %>'>
		<%= value %>
	</div>
<% end %>

app/views/shared/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <nav>
        <ul class="nav">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <li><%= link_to "Chassis", chassises_path %></li>
        </ul>
      </nav>
      <nav>
        <ul class="nav pull-right">
          <% if user_signed_in? %>
            <% @partners.each do |partner| %>
              <li><%= link_to "#{partner.name}", partner %></li>
            <% end %>
            <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
          <% else %>
            <li><%= link_to "Login",  new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/shared/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->