config/routes.rb
Mol::Application.routes.draw do

  namespace :admin do
    root :to => "base#index"
    resources :partners
    resources :users
    resources :uploads
  end

  devise_for :users
  resources :partners do
    resources :items
    resources :file_uploads
  end

  resources :chassises
  match '/help', :to => 'pages#help', :via => 'get'
  root :to => "pages#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  def index
  	@users = User.all
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		flash[:notice] = "New user created."
			redirect_to admin_users_path
  	else
  		flash[:alert] = "Error on user."
			render :action => 'new'
  	end
  end

  def show
  	@user = User.find(params[:id])
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		flash[:notice] = "Update user."
			redirect_to admin_users_path
  	else
  		flash[:alert] = "Error on Updating user."
			render :action => 'edit'
  	end
  end

  def destroy
  	@user = User.find(params[:id]).destroy
  	flash[:notice] = "Delete user."
		redirect_to admin_users_path
  end

  private
  	def user_params
  		params.require(:user).permit(:email, :password)
  	end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
	<p>
		<%= f.label :email %>
		<%= f.email_field :email %>
	</p>
	<p>
		<%= f.label :password %>
		<%= f.password_field :password %>
	</p>
	<%= f.submit %>
<% end %>

app/views/admin/users/edit.html.erb
<h4>Update User</h4>
<%= render 'form' %>

app/views/admin/users/index.html.erb
<h4>Users List</h4>
<%= link_to "Create User", new_admin_user_path %>

<table class="table">
	<thead>
		<tr>
			<th>Email</th>
			<th>Last Logged in?</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= user.email %></td>
			<td><%= user %></td>
			<td>
				<%= link_to "View", [:admin, user] %>
				<%= link_to "Update", [:edit, :admin, user] %>
				<%= link_to "Delete", [:admin, user], :method => :delete, :confirm => "Are you sure?" %>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/admin/users/new.html.erb
<h4>New User</h4>
<%= render 'form' %>

app/views/admin/users/show.html.erb
<h4>User Details</h4>
<h6>#<%= @user.id %></h6>
<h6><%= @user.email %></h6>